// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qFC8N91jL5ruqsAGEgK2CerNKCTLp7s',
    appId: '1:99200104264:web:691c9c4c65b4d7b612e57d',
    messagingSenderId: '99200104264',
    projectId: 'dam-p-final',
    authDomain: 'dam-p-final.firebaseapp.com',
    storageBucket: 'dam-p-final.appspot.com',
    measurementId: 'G-TZHZK0CF0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEHqHrh8kSbyJbQJYE6nNI8roFb7ofRo',
    appId: '1:99200104264:android:870286783716c7d712e57d',
    messagingSenderId: '99200104264',
    projectId: 'dam-p-final',
    storageBucket: 'dam-p-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9tCKTNenGS6t44927gi30iXU2QLpn3A',
    appId: '1:99200104264:ios:fd7d8c8f17b6073d12e57d',
    messagingSenderId: '99200104264',
    projectId: 'dam-p-final',
    storageBucket: 'dam-p-final.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );
}
